version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: conduit
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/conduit
    command: sh -c "npx prisma migrate deploy && npm run start"

  frontend:
    build: ./frontend
    ports:
      - "4100:4100"
    depends_on:
      - backend
    environment:
      - API_ROOT=http://localhost:3000/api
    command: npm start

volumes:
  pgdata: