name: QA Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'cypress/**'
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node-version: '20'
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

  install-deps:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Root Deps
        run: npm ci

      - name: Install Frontend Deps
        working-directory: ./frontend
        run: npm ci

      - name: Install Backend Deps
        working-directory: ./backend
        run: npm ci

  db-migrate-seed:
    runs-on: ubuntu-latest
    needs: install-deps
    services:
      postgres:
        image: postgres:15
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: realworld
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Wait for Postgres
        run: sleep 15

      - name: Push Prisma Schema
        working-directory: ./backend
        run: npx prisma db push --schema=src/prisma/schema.prisma

      - name: Seed DB
        working-directory: ./backend
        run: npx tsx src/prisma/seed.ts

  run-tests:
    runs-on: ubuntu-latest
    needs: db-migrate-seed
    steps:
      - uses: actions/checkout@v3

      - name: Start Backend & Frontend
        run: |
          docker compose up -d --build
          sleep 30

      - name: Run Cypress Tests
        run: npm run cy:run

      - name: Upload Cypress Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: |
            cypress/screenshots
            cypress/videos